version: '3.8'

services:
  web:
    build:
      context: ./ieee
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./club:/club
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres-database
  postgres-database:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ieee
      - POSTGRES_DB=ieee
volumes:
  postgres_data: