version: '3.8'

services:
  web:
    container_name: web-application
    build:
      context: ./ieee
      dockerfile: Dockerfile.prod
    image: 481243181382.dkr.ecr.eu-north-1.amazonaws.com/ieee-ec2:web
    command: gunicorn club.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres-database
      
  postgres-database:
    container_name: postgres-database
    image: 481243181382.dkr.ecr.eu-north-1.amazonaws.com/ieee-ec2:postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: 481243181382.dkr.ecr.eu-north-1.amazonaws.com/ieee-ec2:nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: